parameters:
    mjr.frontend.operations.class: Mjr\Frontend\OperationsBundle\AuthSuccessHandler
    mjr.frontend.operations.u2f_listener.class: Mjr\Frontend\OperationsBundle\Event\U2FregistrationListener
services:
    mjr.frontend.operations.success_handler:
        class: %mjr.frontend.operations.class%
        arguments: ['@security.http_utils', '@service_container', {}]
        tags:
            - { name: 'monolog.logger', channel: 'security'}

    mjr.frontend.operations.u2f_listener:
         class: %mjr.frontend.operations.u2f_listener.class%
         tags:
             - { name: kernel.event_subscriber }