parameters:
    mjr.frontend.operations.class: Mjr\Frontend\OperationsBundle\AuthSuccessHandler
services:
    mjr.frontend.operations.success_handler:
        class: %mjr.frontend.operations.class%
        arguments: ['@security.http_utils', '@service_container', {}]
        tags:
            - { name: 'monolog.logger', channel: 'security'}