parameters:
    mjr_library_profiler.profiler.event.request.class: Mjr\Library\ProfilerBundle\EventListener\RequestListener
    mjr_library_profiler.profiler.console.listener.class: Mjr\Library\ProfilerBundle\EventListener\CommandListener
    mjr_library_profiler.profiler.data_collector.class: Mjr\Library\ProfilerBundle\DataCollector\XhprofCollector
services:
    mjr_library_profiler.listener:
        class: %mjr_library_profiler.profiler.event.request.class%
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onCoreResponse, priority: -10000 }
            - { name: kernel.event_listener, event: kernel.request, method: onCoreRequest, priority: 10000 }
        arguments: ['@data_collector.xhprof', '@service_container']

    mjr_library_profiler.console.listener:
        class: %mjr_library_profiler.profiler.console.listener.class%
        tags:
            - { name: kernel.event_listener, event: console.command, method: onCommand, priority: -10000 }
            - { name: kernel.event_listener, event: console.terminate, method: onTerminate, priority: 10000 }
        arguments: ['@data_collector.xhprof', '@service_container']
        calls:
            - [setEnabled, ['%mjr_library_profiler.command%']]
            - [setOptionName, ['%mjr_library_profiler.command_option_name%']]
            - [setFilters, ['%mjr_library_profiler.command_exclude_patterns%']]
            - [setWebLocation, ['%mjr_library_profiler.location_web%']]

    data_collector.xhprof:
        class: %mjr_library_profiler.profiler.data_collector.class%
        tags:
            - { name: data_collector, template: 'MjrLibraryProfilerBundle:Collector:xhprof', id: xhprof }
        arguments: ['@service_container', '@?logger', '@?doctrine']
