imports:
    - { resource: config.yml }

parameters:
    web.profiler.cache.class: Mjr\Library\ToolsBundle\Profiler\RedisProfilerStorage

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

mjr_library_tools:
    data_collector:
        show_filelist:  true

    WebProfiler:
        routing:
            enabled: true
            display_in_wdt: false
        assetic:
            enabled: true
            display_in_wdt: false
        twig:
            enabled: true
            display_in_wdt: false
        opcache:
            enabled: true
    profiler:
        defaultStorage: false
        class: %web.profiler.cache.class%
        dsn: %redis_debug%
        ttl: 3600


monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]
        console:
            type:   console
            bubble: false
            channels: [!event, !doctrine]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

#swiftmailer:
#    delivery_address: me@example.com



web_profiler:
    toolbar: true
    intercept_redirects: false