imports:
    - { resource: parameters.yml }
    - { resource: system-config.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: de
    ambta_doctrine_encrypt.class: Mjr\Library\ToolsBundle\Encryption\Rijndael256Encryptor


#Doctrine Encryption
ambta_doctrine_encrypt:
    secret_key:           %encryptionsecret% # Your own random 256 bit key (32 characters)
    encryptor:            rijndael256 # rijndael256 or rijndael128
    encryptor_class:      %ambta_doctrine_encrypt.class%

# Assetic Configuration
assetic:
    assets:
        frontend_css:
            inputs:
                - %kernel.root_dir%/../usr/Mjr/Theme/AdminLTEBundle/bootstrap/bootstrap.less
                - %kernel.root_dir%/../var/vendor/components/font-awesome/less/font-awesome.less
                - %kernel.root_dir%/../usr/Mjr/Library/ToolsBundle/Resources/css/select2.css
            filters:
                - lessphp
            output: css/bootstrap.css
        frontend_theme_css:
            inputs:
                - %kernel.root_dir%/../usr/Mjr/Theme/AdminLTEBundle/build/less/AdminLTE.less
                - %kernel.root_dir%/../usr/Mjr/Theme/AdminLTEBundle/build/less/skins/_all-skins.less
            filters:
                - lessphp
            output: css/theme.css
        moment_js:
            inputs:
                - %kernel.root_dir%/../var/vendor/moment/moment/moment.js
            output: js/moment.js
        #jQuery
        jquery_js:
            inputs:
                - %kernel.root_dir%/../var/vendor/components/jquery/jquery.js
            output: js/jquery.js
        bootstrap_js:
            inputs:
                - %kernel.root_dir%/../var/vendor/twbs/bootstrap/js/transition.js
                - %kernel.root_dir%/../var/vendor/twbs/bootstrap/js/alert.js
                - %kernel.root_dir%/../var/vendor/twbs/bootstrap/js/button.js
                - %kernel.root_dir%/../var/vendor/twbs/bootstrap/js/carousel.js
                - %kernel.root_dir%/../var/vendor/twbs/bootstrap/js/collapse.js
                - %kernel.root_dir%/../var/vendor/twbs/bootstrap/js/dropdown.js
                - %kernel.root_dir%/../var/vendor/twbs/bootstrap/js/modal.js
                - %kernel.root_dir%/../var/vendor/twbs/bootstrap/js/tooltip.js
                - %kernel.root_dir%/../var/vendor/twbs/bootstrap/js/popover.js
                - %kernel.root_dir%/../var/vendor/twbs/bootstrap/js/scrollspy.js
                - %kernel.root_dir%/../var/vendor/twbs/bootstrap/js/tab.js
                - %kernel.root_dir%/../var/vendor/twbs/bootstrap/js/affix.js
                - %kernel.root_dir%/../usr/Mjr/Library/ToolsBundle/Resources/js/bootbox.js
                - %kernel.root_dir%/../usr/Mjr/Library/ToolsBundle/Resources/js/growl.js
                - %kernel.root_dir%/../usr/Mjr/Library/ToolsBundle/Resources/js/select2.full.min.js
            output: js/bootstrap.js
        bootstrap_switch_js:
            inputs:
                - %kernel.root_dir%/../var/vendor/components/bootstrap-switch/dist/js/bootstrap-switch.js
            output: js/bootstrap-switch.js
        mopa_bundle_js:
            inputs:
                - %kernel.root_dir%/../var/vendor/mopa/bootstrap-bundle/Mopa/Bundle/BootstrapBundle/Resources/public/js/mopabootstrap-collection.js
                - %kernel.root_dir%/../var/vendor/mopa/bootstrap-bundle/Mopa/Bundle/BootstrapBundle/Resources/public/js/mopabootstrap-subnav.js
            output: js/mopa.js
        frontend_js:
            inputs:
                - %kernel.root_dir%/../usr/Mjr/Theme/AdminLTEBundle/dist/js/app.js
            output: js/app.js
        font_awesom_otf:
            inputs:
                - %kernel.root_dir%/../var/vendor/components/font-awesome/fonts/FontAwesome.otf
            output: fonts/FontAwesome.otf
        font_awesom_eot:
            inputs:
                - %kernel.root_dir%/../var/vendor/components/font-awesome/fonts/fontawesome-webfont.eot
            output: fonts/fontawesome-webfont.eot
        font_awesom_svg:
            inputs:
                - %kernel.root_dir%/../var/vendor/components/font-awesome/fonts/fontawesome-webfont.svg
            output: fonts/fontawesome-webfont.svg
        font_awesom_ttf:
            inputs:
                - %kernel.root_dir%/../var/vendor/components/font-awesome/fonts/fontawesome-webfont.ttf
            output: fonts/fontawesome-webfont.ttf
        font_awesom_woff:
            inputs:
                - %kernel.root_dir%/../var/vendor/components/font-awesome/fonts/fontawesome-webfont.woff
            output: fonts/fontawesome-webfont.woff
        font_awesom_woff2:
            inputs:
                - %kernel.root_dir%/../var/vendor/components/font-awesome/fonts/fontawesome-webfont.woff2
            output: fonts/fontawesome-webfont.woff2

    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ MjrLibraryToolsBundle ]
    #java: /usr/bin/java
    filters:
        lessphp:
            file: %kernel.root_dir%/../var/vendor/oyejorge/less.php/lessc.inc.php
            # Formatter options: compressed, lessjs, classic
            formatter: "compressed"
            preserve_comments: false
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        #Cache Driver
        metadata_cache_driver:  redis
        query_cache_driver:     redis
        result_cache_driver:    redis
        #Second Level Cache
        second_level_cache:
            enabled:            true
            log_enabled:        true
            region_cache_driver: redis
         #Gedmo Package extension for Symfony and Doctrine
        mappings:
            gedmo_tree:
                type: annotation
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.root_dir%/../var/vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                alias: GedmoTree
                is_bundle: false
            gedmo_sortable:
                type: annotation
                prefix: Gedmo\Sortable\Entity
                dir: "%kernel.root_dir%/../var/vendor/gedmo/doctrine-extensions/lib/Gedmo/Sortable/Entity"
                alias: GedmoTree
                is_bundle: false
            gedmo_loggable:
                type: annotation
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.root_dir%/../var/vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                alias: GedmoLoggable # (optional) it will default to the name set for the mappingmapping
                is_bundle: false

        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true

doctrine_migrations:
    dir_name: "%kernel.root_dir%/../var/Migrations"
    namespace: Application\Migrations
    table_name: system_migration_versions
    name: Application Migrations

#Elastic Search
fos_elastica:
    clients:
        default:
            host: %elastic_host%
            port: %elastic_port%
    indexes:
        app:
            index_name: %elastic_index%

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

#Bootstrap and Less Integration
mopa_bootstrap:
    form:
        show_legend: true
        show_child_legend: true
        error_type: inline
        templating: true
        render_fieldset: true
        render_collection_item: true
        render_required_asterisk: true
        render_optional_text: true
        checkbox_label: 'both'
    menu: ~
    icons:
        icon_set: fontawesome4

mjr_library_errbit:
    api_key: "%errbit_api_key%"
    async: %errbit_async%
    host: "%errbit_host%"
    secure: %errbit_secure%
    ignored_exceptions:
        - Symfony\Component\HttpKernel\Exception\HttpException


snc_redis:
    clients:
        #Default Caching
        default:
            type:   phpredis
            alias:  default
            dsn:    %redis_cache%
        #Session Handling
        session:
            type:   phpredis
            alias:  session
            dsn:    %redis_session%
        #Doctrine
        doctrine:
            type:   phpredis
            alias:  doctrine
            dsn:    %redis_doctrine%
        swiftmailer:
            type:   phpredis
            alias:  swiftmailer
            dsn:    %redis_swiftmailer%
    #Session Config
    session:
        client: session
        prefix: cp
    doctrine:
      metadata_cache:
          client: doctrine
          entity_manager: default
          document_manager: default
      query_cache:
          client: doctrine
          entity_manager: default
      result_cache:
          client: doctrine
          entity_manager: [default]
    swiftmailer:
        client: swiftmailer
        key: swiftmailer


#Stof ORM Extensions
stof_doctrine_extensions:
    default_locale: "%locale%"
    translation_fallback: true
    orm:
        default:
            timestampable: true
            blameable: true
            softdeleteable: true
            sortable: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:
        type: service
        id: snc_redis.swiftmailer.spool




# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        SystemProjectLogoSmall: %system_config_logo_small%
        SystemProjectLogoLarge: %system_config_logo_large%
        SystemProjectName: %system_config_project_name%
        SystemCompanyName: %system_config_company_name%
        SystemCompanyLink: %system_config_company_link%
        SystemLink: %system_config_company_link%
