parameters:
    mjr_library_tools.twig.budles.extension.class: Mjr\Library\ToolsBundle\Twig\BundleExtensions

services:
    mjr_library_tools.twig.bundles.extension:
        class: %mjr_library_tools.twig.budles.extension.class%
        arguments: ['@service_container']
        tags:
          - { name: twig.extension }
