parameters:
    mjr_library_tools.data_collector.assetic.class: Mjr\Library\ToolsBundle\DataCollector\AsseticDataCollector

services:
    mjr_library_tools.data_collector.assetic:
        class: %mjr_library_tools.data_collector.assetic.class%
        public: false
        tags:
            - { name: data_collector, template: 'MjrLibraryToolsBundle:Collector:assetic.html.twig', id: library_assetic }
        arguments: ['@service_container', '%mjr_library_tools.webprofiler.assetic.display_in_wdt%']